# Generated by Django 2.2.4 on 2020-01-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=9)),
                ('name', models.IntegerField(default=0)),
                ('idnum', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=9)),
                ('nickname', models.CharField(max_length=21)),
                ('firstname', models.CharField(max_length=21)),
                ('lastname', models.CharField(max_length=21)),
                ('idnum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='residencyEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=21)),
            ],
        ),
    ]
