# Generated by Django 2.2.4 on 2020-01-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='uid',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
