# Generated by Django 2.2.4 on 2020-01-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20200111_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Member'),
        ),
    ]
